
import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export const useSurveyStore = create(persist((set) => ({

    data: {
        completionDate: null,
        surveyUnderstanding: null,
        selectedGender: null,
        bornPlace: null,
        birthday: null,
        birthMonth: null,
        birthYear: null,
        age: null,
        documentType: '',
        id: null,
        bloodGroup: null,
        factorRH: null,
        healthScheme: null,
        nameHealthScheme: null,
        ipsAttention: null,
        maritalStatus: null,
        educationalLevel: null,
        donationCity: null,
        residenceAddress: null,
        neighborhood: null,
        municipality: null,
        department: null,
        landline: null,
        mobile: null,
        occupation: null,
        workPhone: null,
        email: null,
        question1: null,
        question1HowLongAgo: null,
        question1Where: null,
        question1AdverseReaction: null,
        question1WhatDidYouSubmit: null,
        question2: null,
        question3: null,
        question4: null,
        question5: null,
        question6: null,
        question7: null,
        question7WhichCondition: null,
        question7DizzinessOrSeizures: null,
        question7Allergies: null,
        question7AllergyToWhat: null,
        question8: null,
        question8WhichMedication: null,
        question9: null,
        question9Diarrhea: null,
        question9NightSweats: null,
        question9PersistentCough: null,
        question9SwollenLymphNodes: null,
        question9SkinLesions: null,
        question9Fever: null,
        question10: null,
        question10WhichVaccine: null,
        question11: null,
        question12: null,
        question13: null,
        question14: null,
        question14Homeless: null,
        question14InjectDrugs: null,
        question15: null,
        question16: null,
        question17: null,
        question18: null,
        question19: null,
        question20: null,
        question21: null,
        question22: null,
        question23: null,
        question24: null,
        question24WhichDisease: null,
        question25: null,
        question26: null,
        question27: null,
        question27Where: null,
        question27HowLongAgo: null,
        question28: null,
        question28DoubtsAnswered: null,
        question29ActivityAfterDonation: null,
        lastMenstruationDate: null,
        pregnancyCount: null,
        birthsCount: null,
        cesareanCount: null,
        abortionsCount: null,
        pregnantOrRelatedEventsLastYear: null,
        pregnantOrRelatedEventsLastYearWhich: null,
        donorObservationSummary: null,
        postDonationRecommendationsGiven: null,
        finalObservations: null,
        siheviVerificationBloodBankSoftware: null,
    },
    // Funcion generica para actualizar cualquier campo de Data
    setField: (field, value) =>
        set((state) => ({
            data: {
                ...state.data,
                [field]: value,
            }
        }))
}), {
    name: 'survey-storage',      // nombre en localStorage
    getStorage: () => localStorage
}))
